name: Brian Parks
markdown: kramdown
pygments: true
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /blog/page:num
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "posts"
    values:
      layout: post
