name: Brian Parks
markdown: redcarpet
pygments: true
plugins:
  - jekyll-paginate
paginate: 10
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "posts"
    values:
      layout: post
